class Config:
    REGRESSION_TRAIN = 0.8
    REGRESSION_VALIDATION = 0.1
    REGRESSION_N_ROUNDS = 250
    REGRESSION_EPOCHS = 1000
    REGRESSION_LEARNING_RATE = 0.0001
    REGRESSION_EPSILON = 0.0001
    REGRESSION_PLOT_GRAPH = True

    CLASSIFICATION_TRAIN = 0.8
    CLASSIFICATION_VALIDATION = 0.1
    CLASSIFICATION_N_ROUNDS = 250
    CLASSIFICATION_EPOCHS = 500
    CLASSIFICATION_LEARNING_RATE = 0.0001
    CLASSIFICATION_EPSILON = 0.0001
    CLASSIFICATION_PLOT_GRAPH = True