class Config:
    PLOT_REGRESSION_LINE = False
    REGRESSION_TRAIN = 0.8
    REGRESSION_EPOCHS = 100
    REGRESSION_VALIDATION = 0.1
    REGRESSION_N_ROUNDS = 250
    REGRESSION_LEARNING_RATE = 0.1
    REGRESSION_EPSILON = 0.0001
    REGRESSION_MLP_LAYERS = [2, 1]
    REGRESSION_MLP_SUPERFITTED_LAYERS = [32, 16, 8]
    REGRESSION_MLP_UNDERFITTED_LAYERS = [1]
    REGRESSION_MLP_OUTPUT_SIZE = 1
    REGRESSION_MLP_TOLLERATION = 10
    REGRESSION_PLOT_GRAPH = False

    CLASSIFICATION_TRAIN = 0.8
    CLASSIFICATION_VALIDATION = 0.1
    CLASSIFICATION_N_ROUNDS = 5
    CLASSIFICATION_EPOCHS = 1000
    CLASSIFICATION_LEARNING_RATE = 0.1
    CLASSIFICATION_EPSILON = 0.00000001
    CLASSIFICATION_PLOT_GRAPH = True
    CLASSIFICATION_MLP_TOLLERATION = 10
    CLASSIFICATION_MLP_OUTPUT_SIZE = 1
    CLASSIFICATION_MLP_LAYERS = [2, 1]
    CLASSIFICATION_MLP_OVERFITTED_LAYERS = [32, 16, 8]
    CLASSIFICATION_MLP_UNDERFITTED_LAYERS = [1]
    
    CLASSIFICATION_MULTICLASS_MLP_LAYERS = [2]
    CLASSIFICATION_MULTICLASS_MLP_OUTPUT_SIZE = 3
    CLASSIFICATION_MULTICLASS_MLP_TOLLERATION = 10
    CLASSIFICATION_MULTICLASS_MLP_OVERFITTED_LAYERS = [32, 16, 8]
    CLASSIFICATION_MULTICLASS_MLP_UNDERFITTED_LAYERS = [1]
    CLASSIFICATION_MULTICLASS_LEARNING_RATE = 0.1
    CLASSIFICATION_MULTICLASS_EPSILON = 0.0001
    CLASSIFICATION_MULTICLASS_EPOCHS = 1000
    CLASSIFICATION_MULTICLASS_N_ROUNDS = 100