class Config:
    PLOT_REGRESSION_LINE = False
    REGRESSION_TRAIN = 0.8
    REGRESSION_EPOCHS = 100
    REGRESSION_VALIDATION = 0.1
    REGRESSION_N_ROUNDS = 250
    REGRESSION_LEARNING_RATE = 0.1
    REGRESSION_EPSILON = 0.0001
    REGRESSION_PLOT_GRAPH = False

    CLASSIFICATION_TRAIN = 0.8
    CLASSIFICATION_VALIDATION = 0.1
    CLASSIFICATION_N_ROUNDS = 5
    CLASSIFICATION_EPOCHS = 1000
    CLASSIFICATION_LEARNING_RATE = 0.1
    CLASSIFICATION_EPSILON = 0.00000001
    CLASSIFICATION_PLOT_GRAPH = True